version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repository

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - run: mkdir -p workspace
      - checkout
      - persist_to_workspace:
          root: workspace
          paths: .
  build:
    <<: *container_config
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mvn -B -DskipTests clean package
  test:
    <<: *container_config
    steps:
      - run: mvn test

workflows:
  version: 2
  build_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
