version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repository

jobs:
  checkout_build_test:
    <<: *container_config
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
      - run: mvn test